services:
  db:
    image: mysql:8.4
    container_name: marac-db
    environment:
      MYSQL_DATABASE: marac
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - marac-network

  # GRUP APACHE 
  apache:
    build:
      context: .
      dockerfile: ./docker-apache/Dockerfile
    container_name: marac-apache
    profiles: ["apache"] # <--- Hanya jalan jika dipanggil
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - marac-network

  # GRUP NGINX (Terdiri dari Nginx + PHP-FPM)
  php-fpm:
    build:
      context: .
      dockerfile: ./docker-nginx/Dockerfile
    container_name: marac-php-fpm
    profiles: ["nginx"] # <--- Ikut grup nginx
    volumes:
      - .:/var/www/html
    networks:
      - marac-network

  nginx:
    image: nginx:alpine
    container_name: marac-nginx
    profiles: ["nginx"] # <--- Ikut grup nginx
    ports:
      - "8000:80"
      - "5173:5173" # misal pakai vite
    volumes:
      - .:/var/www/html
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - marac-network

networks:
  marac-network:
    driver: bridge

volumes:
  mysql_data: